import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

import Link from "next/link"
import { Home, Menu, User, Users } from "lucide-react"

import { Button } from "@/components/ui/button"

import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet"
import { Toaster } from "@/components/ui/toaster"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />

        <div className="flex min-h-screen w-full flex-col">
          <header className="sticky top-0 flex h-16 items-center gap-4 border-b bg-background px-4 md:px-6">
            <nav className="hidden flex-col gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
              <Link
                href="/"
                className="text-muted-foreground transition-colors hover:text-foreground flex gap-1 items-center justify-center"
              >
                <Home className="size-4" />
                Anasayfa
              </Link>
              <Link
                href="/applicant"
                className="text-muted-foreground transition-colors hover:text-foreground flex gap-1 items-center justify-center"
              >
                <User className="size-4" />
                Aday
              </Link>
              <Link
                href="/human-resources"
                className="text-muted-foreground transition-colors hover:text-foreground flex gap-1 items-center justify-center"
              >
                <Users className="size-4" />
                <p>İnsan</p>
                <p>Kaynakları</p>
              </Link>
            </nav>
            <Sheet>
              <SheetTrigger asChild>
                <Button
                  variant="outline"
                  size="icon"
                  className="shrink-0 md:hidden"
                >
                  <Menu className="h-5 w-5" />
                  <span className="sr-only">Toggle navigation menu</span>
                </Button>
              </SheetTrigger>
              <SheetContent side="left">
                <nav className="grid gap-6 text-lg font-medium">
                  <Link
                    href="/"
                    className="flex items-center gap-2 text-lg font-bold text-primary"
                  >
                    Shaolin Keşişleri
                  </Link>
                  <Link
                    href="/"
                    className="text-muted-foreground hover:text-foreground"
                  >
                    Anasayfa
                  </Link>
                  <Link
                    href="/applicant"
                    className="text-muted-foreground hover:text-foreground"
                  >
                    Aday
                  </Link>
                  <Link
                    href="/human-resources"
                    className="text-muted-foreground hover:text-foreground"
                  >
                    İnsan Kaynakları
                  </Link>
                </nav>
              </SheetContent>
            </Sheet>
            <div className="flex w-full items-center gap-4 md:ml-auto md:gap-2 lg:gap-4">
              <div className="ml-auto flex-1 sm:flex-initial">
                <Link href="/" className="font-bold text-primary">
                  Shaolin Keşişleri
                </Link>
              </div>
            </div>
          </header>
          <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 bg-muted/40 p-4 md:gap-8 md:p-10">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
